[package]
name = "infrastructure"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Open-source football management simulator"
repository = "https://github.com/openfootball-manager/openfootball"

[dependencies]
