name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Fix Git line endings for PNGs
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
          git reset --hard

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy, rustfmt

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
          cache-dependency-path: src/tauri/pnpm-lock.yaml

      - name: Install frontend dependencies
        working-directory: src/tauri
        run: pnpm install --frozen-lockfile

      - name: Build frontend
        working-directory: src/tauri/
        run: pnpm run build

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Run Clippy (workspace)
        run: cargo clippy --workspace --exclude tauri --all-targets --all-features -- -D warnings

      - name: Run Clippy (tauri)
        working-directory: src/tauri/src-tauri
        env:
          TAURI_SKIP_ICON_CHECK: "true"
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Run tests
        run: cargo test --all

      - name: Install Tauri CLI
        run: cargo install tauri-cli --locked

      - name: Build Tauri app
        run: cargo tauri build
